name: scalable
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # CORE
  dartz: ^0.10.1
  bloc_concurrency: ^0.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  kt_dart: ^0.10.0
  faker: ^2.0.0
  freezed_annotation: ^2.0.3
  clock: ^1.1.0

  # PRESENTATION
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^4.2.1
  flutter_bloc: ^8.0.1

  # APPLICATION
  bloc: ^8.0.3

  # DOMAIN

  # INFRASTRUCTURE
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
