name: scalable
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # CORE
  dartz: ^0.10.1
  bloc_concurrency: ^0.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  kt_dart: ^0.10.0
  faker: ^2.0.0
  freezed_annotation: ^1.1.0
  clock: ^1.1.0

  # PRESENTATION
  flutter:
    sdk: flutter
  auto_route: ^3.2.4
  flutter_bloc: ^8.0.1
  # cupertino_icons: ^1.0.2
  # macos_ui: ^0.12.4
  # fluent_ui: ^3.11.0
  # yaru: ^0.2.5
  # yaru_icons: ^0.2.1

  # APPLICATION
  bloc: ^8.0.3

  # DOMAIN

  # INFRASTRUCTURE
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
